defaults: &defaults
  working_directory: ~/deploy.am
  docker:
  - image: inductor/firebase-cli-alpine:latest

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: "Run yarn install"
        command: yarn
    - save_cache:
        key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/deploy.am/node_modules
        - ~/.cache/yarn/
  deploy:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: "Vue CLI build"
        command: yarn && yarn generate
    - run:
        name: "Deploy"
        command: firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
