version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run yarn install"
          command: yarn
      - run:
          name: "Vue CLI build"
          command: yarn build
#      - run:
#          name: "Test Website"
#          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - run:
          name: "Deploy"
          command: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
