version: 2
jobs:
  build:
    docker:
      - image: inductor/firebase-cli-alpine
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: "Run yarn install"
          command: yarn
      - run:
          name: "Vue CLI build"
          command: yarn generate
      - save_cache:
          key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules
            - ~/.cache/yarn/
      - run:
          name: "Deploy"
          command: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
