version: 2.1

executors:
  default:
    working_directory: ~/deploy.am
    docker:
      - image: inductor/firebase-cli-alpine:latest
commands:
  restore_modules:
    steps:
      - restore_cache:
          name: Restore node dependencies
          key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}

  save_modules:
    steps:
      - save_cache:
          name: Cache node dependencies
          key: deploy-am-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/deploy.am/node_modules

jobs:
  build:
    executor:
      name: default
    steps:
    - checkout
    - restore_modules
    - run:
        name: "Run npm install"
        command: yarn install
    - save_modules
  deploy:
    executor:
      name: default
    steps:
    - checkout
    - restore_modules
    - run:
        name: "Vue CLI build"
        command: yarn generate
    - run:
        name: "Deploy"
        command: firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
